Format install script

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -7,36 +7,36 @@ source "${currentDir}/utils.sh"
 
 install() {
 
-  if [ "${ASDF_INSTALL_TYPE}" == "ref" ]; then
-    echo "Only binary versions are supported"
-    exit 1
-  fi
-  
-  local urlPrefix="${FLUTTER_STORAGE_BASE_URL}/flutter_infra_release/releases"
-  
-  local versionListUrl="${FLUTTER_STORAGE_BASE_URL}/flutter_infra_release/releases/releases_macos.json"
-  
-  if [ "$(uname -s)" == "Linux" ]; then
-    versionListUrl="${FLUTTER_STORAGE_BASE_URL}/flutter_infra_release/releases/releases_linux.json"
-  fi
-  
-  local escapedInstallVersion=$(echo $ASDF_INSTALL_VERSION | sed 's/\./\\\./g;s/\+/\\\+/g')
+	if [ "${ASDF_INSTALL_TYPE}" == "ref" ]; then
+		echo "Only binary versions are supported"
+		exit 1
+	fi
 
-  local filePath=$(curl -sL "${versionListUrl}" | "${JQ_BIN}" -r --arg VERSION "${escapedInstallVersion}" '.releases[] | select((.version + "-" + .channel) | test("^v?" + $VERSION)) | .archive')
+	local urlPrefix="${FLUTTER_STORAGE_BASE_URL}/flutter_infra_release/releases"
 
-  if [ -z "${filePath}" ]; then
-    echo "Cannot find the download url for the version: ${ASDF_INSTALL_VERSION}"
-    exit 1
-  fi
+	local versionListUrl="${FLUTTER_STORAGE_BASE_URL}/flutter_infra_release/releases/releases_macos.json"
 
-  local url="${urlPrefix}/${filePath}"
-  local fileName="${url##*/}"
+	if [ "$(uname -s)" == "Linux" ]; then
+		versionListUrl="${FLUTTER_STORAGE_BASE_URL}/flutter_infra_release/releases/releases_linux.json"
+	fi
 
-  mkdir -p "${ASDF_INSTALL_PATH}"
-  cd "${ASDF_INSTALL_PATH}" || exit 1
-  curl -OJL "${url}"
-  tar xf "${fileName}" --strip 1
-  rm -f "${fileName}"
+	local escapedInstallVersion=$(echo $ASDF_INSTALL_VERSION | sed 's/\./\\\./g;s/\+/\\\+/g')
+
+	local filePath=$(curl -sL "${versionListUrl}" | "${JQ_BIN}" -r --arg VERSION "${escapedInstallVersion}" '.releases[] | select((.version + "-" + .channel) | test("^v?" + $VERSION)) | .archive')
+
+	if [ -z "${filePath}" ]; then
+		echo "Cannot find the download url for the version: ${ASDF_INSTALL_VERSION}"
+		exit 1
+	fi
+
+	local url="${urlPrefix}/${filePath}"
+	local fileName="${url##*/}"
+
+	mkdir -p "${ASDF_INSTALL_PATH}"
+	cd "${ASDF_INSTALL_PATH}" || exit 1
+	curl -OJL "${url}"
+	tar xf "${fileName}" --strip 1
+	rm -f "${fileName}"
 }
 
 download_jq_if_not_exists
